# Generated by Django 4.2.7 on 2023-11-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_picture.jpeg', upload_to=''),
        ),
    ]
