# Generated by Django 5.0 on 2023-12-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
